on: [push]

jobs:
  bugsnagReportBuild:
    runs-on: ubuntu-latest
    name: Bugsnag - Report Build
    steps:
    - name: report
      uses: lhansford/bugsnag-report-build-action@1.0.6
      with:
        apiKey: ${{ secrets.bugsnag_api_key }}
        appVersion: 1.0.6
        failCiIfError: true
