on: [push]

jobs:
  bugsnagReportBuild:
    runs-on: ubuntu-latest
    name: Bugsnag - Report Build
    steps:
    - name: report
      uses: lhansford/bugsnag-report-build-action@1.0.2
      with:
        apiKey: 12345
        failCiIfError: true
